close all; clear all;

saved_dir = "..\251127 trilayer\results_TTT_0048_3_crop_1";

opts = load(strcat(saved_dir,'\','parameters_opts.mat'));
opts_skel = load(strcat(saved_dir,'\','parameters_opts_skel.mat'));
saved_node_point = load(strcat(saved_dir,'\','node_point.mat'));


line_bending_interactive('..\raw data\TTT_0048_3_crop_1.tif','mutual',opts.opts, ...
    opts_skel.opts_skel_used,true,saved_node_point.node_point);


%% ----------------- 사용했던 파라미터들 --------------

% % results_TTT_0012_3_crop_1
% opts_skel = struct( ...
%   'invert', true,...
%   'clachClip',0.01,...
%   'gaussSigma', 1.5, ...       % 노이즈 더 누르고
%   'method','adaptive', ...
%   'adaptWin', 51, ...
%   'adaptSens', 0.3, ...       % 보수적으로 ON (놓치지 않도록)
%   'gaborWavelengths', [2 3 4],... % 가는 선 대응
%   'gaborTheta', 0:15:165, ...
%   'morphOpen',0, ...
%   'morphClose', 0, ...
%   'minObject', 100, ...
%   'spurPrune', Inf);




%% --------------------- 참조용 파라미터들 --------------------

% opts_skel = struct( ...
%   'method','gabor', ...
%   'gaussSigma', 1.5, ...       % 노이즈 더 누르고
%   'gaborWavelengths', [2 3 4],... % 가는 선 대응
%   'gaborTheta', 0:10:170, ...
%   'adaptWin', 71, ...
%   'adaptSens', 0.40, ...       % 보수적으로 ON (놓치지 않도록)
%   'morphOpen', 1, ...
%   'morphClose', 2, ...
%   'minObject', 60, ...
%   'spurPrune', 6);

% opts_skel = struct( ...
%   'method','gabor', ...
%   'gaussSigma', 1.0, ...
%   'gaborWavelengths', [3 4 5], ...
%   'gaborTheta', 0:15:165, ...
%   'adaptWin', 51, ...
%   'adaptSens', 0.48, ...       % (0.45→0.48) 조금 더 공격적으로 ON
%   'morphOpen', 2, ...          % 열기 강화(잡영 제거)
%   'morphClose', 1, ...
%   'minObject', 120, ...        % 작은 조각 과감히 제거
%   'spurPrune', 10);            % 짧은 가시 적극 제거

% opts_skel = struct( ...
%   'method','gabor', ...
%   'gaussSigma', 1.2, ...       % (1.0→1.2) 약간 더 블러
%   'gaborWavelengths', [4 6 8],... % 선 폭이 조금 굵다 가정
%   'gaborTheta', 0:10:170, ...  % 방향 분해능↑ (15→10도 간격)
%   'adaptWin', 61, ...          % 로컬 윈도우 조금 키움
%   'adaptSens', 0.42, ...       % (0.45→0.42) 이진화 더 보수적
%   'morphOpen', 1, ...          % 열기 약화(연결 유지)
%   'morphClose', 2, ...         % 닫기 강화(틈 메우기)
%   'minObject', 700, ...
%   'spurPrune', 6);             % 너무 과하게 가지치지 않음