opts = struct( ...
  'pairMode','quadrant', ...   % 또는 'knn'
  'maxPairDist', Inf, ...
  'maxArcChord', 1.30, ...
  'maxDegree', 4,...
  'nmPerPx',1.7, ...
  'mc_jitter', 3);

line_bending_interactive('2nd_peak_region_3_cropped.png','mutual',opts);